In [63]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pickle
import os


In [64]:
# %cd ../utils

import sys
sys.path.append('/home/maria/code/mariajoi/flightdelay/')

from flightdelay.utils.mytrans import MyTrans


In [65]:
%pwd


'/home/maria/code/mariajoi/flightdelay/flightdelay/pickle'

In [66]:
df = pd.read_csv("../data/130k_zeros_removed.csv")
df = df.drop("Unnamed: 0", axis = 1)


In [67]:

X = df.drop(columns=['Tail_Number', 'CarrierDelay', 'WeatherDelay', 'NASDelay',
       'SecurityDelay', 'LateAircraftDelay',
             'Distance', 'ArrTime', 'ArrDelay', 'ArrDelayMinutes', 'ArrDel15',
       'ArrivalDelayGroups','CRSDepTime', 'CRSArrTime' , 'Cancelled', 'CancellationCode',
       'Diverted', 'CRSElapsedTime', 'ActualElapsedTime', 'AirTime', 'DepTime', 'DepDelay',
       'DepDelayMinutes', 'DepDel15', 'DepartureDelayGroups',
        'DestCityName', 'DestState', 'OriginCityName', 'OriginState', 'DestAirportID',
     'Flight_Number_Operating_Airline', 'OriginAirportID','FlightDate','DayofMonth'])

X.head(5)


Month  DayOfWeek Operating_Airline Origin Dest DepTimeBlk ArrTimeBlk  \
0      1          7                AA    CMH  MIA  0600-0659  0900-0959   
1      1          5                WN    AUS  ELP  1900-1959  2000-2059   
2      1          7                YX    GSO  LGA  0600-0659  0800-0859   
3      1          3                B6    LAS  JFK  1300-1359  2100-2159   
4      1          2                AA    ORD  LGA  1300-1359  1600-1659   

   DistanceGroup  
0              4  
1              3  
2              2  
3              9  
4              3

In [68]:
%pwd


'/home/maria/code/mariajoi/flightdelay/flightdelay/pickle'

In [69]:
trans = MyTrans()
trans.fit(X)


MyTrans()

In [89]:
X_trans = trans.transform(X)
X_trans = X_trans.drop(columns=['groups_ArrTimeBlk', 'DistanceGroup'])
X_trans


Operating_Airline Origin Dest     Month_sin  Month_cos  DayOfWeek_sin  \
0                     AA    CMH  MIA  5.000000e-01   0.866025  -2.449294e-16   
1                     WN    AUS  ELP  5.000000e-01   0.866025  -9.749279e-01   
2                     YX    GSO  LGA  5.000000e-01   0.866025  -2.449294e-16   
3                     B6    LAS  JFK  5.000000e-01   0.866025   4.338837e-01   
4                     AA    ORD  LGA  5.000000e-01   0.866025   9.749279e-01   
...                  ...    ...  ...           ...        ...            ...   
130378                MQ    SGF  DFW -2.449294e-16   1.000000  -2.449294e-16   
130379                B6    FLL  JFK -2.449294e-16   1.000000   7.818315e-01   
130380                OO    SPI  DFW -2.449294e-16   1.000000   9.749279e-01   
130381                AA    PHX  SAT -2.449294e-16   1.000000  -4.338837e-01   
130382                YX    IND  JFK -2.449294e-16   1.000000  -4.338837e-01   

        DayOfWeek_cos groups_DepTimeBlk  
0            1.000000           morning  
1           -0.222521             night  
2            1.000000           morning  
3           -0.900969           daytime  
4           -0.222521           daytime  
...               ...               ...  
130378       1.000000           daytime  
130379       0.623490             night  
130380      -0.222521           morning  
130381      -0.900969           daytime  
130382      -0.900969             night  

[130383 rows x 8 columns]

In [90]:
preproc = pickle.load(open("../pickle/preproc_nottrans_notfit_.pkl","rb"))
preproc


ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse=False),
                                 <sklearn.compose._column_transformer.make_column_selector object at 0x7f8e4514ebc0>)])

In [91]:
preproc.fit(X_trans)


/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse=False),
                                 <sklearn.compose._column_transformer.make_column_selector object at 0x7f8e4514ebc0>)])

In [92]:
X_final = preproc.transform(X_trans)
X_final = pd.DataFrame(X_final)

X_final.head(5)


0    1    2    3    4    5    6    7    8    9    ...  761  762  763  764  \
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0   
4  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0   

   765  766  767       768           769       770  
0  1.0  0.0  0.5  0.866025 -2.449294e-16  1.000000  
1  0.0  1.0  0.5  0.866025 -9.749279e-01 -0.222521  
2  1.0  0.0  0.5  0.866025 -2.449294e-16  1.000000  
3  0.0  0.0  0.5  0.866025  4.338837e-01 -0.900969  
4  0.0  0.0  0.5  0.866025  9.749279e-01 -0.222521  

[5 rows x 771 columns]

In [75]:
# selected_columns = ['DistanceGroup', 'Month_sin', 'Month_cos', 'DayOfWeek_sin', 'DayOfWeek_cos']
# all_transformed_cols = trans.transform(X_trans).columns
# selected_transformed_cols = all_transformed_cols.intersection(selected_columns)
# selected_transformed_cols


In [ ]:
# X_transformed = pd.DataFrame(
#     preproc_basic.transform(X),
#     columns=np.concatenate([
#     preproc_basic.named_steps['columntransformer'].named_transformers_['onehotencoder'].get_feature_names_out(),
#     selected_transformed_cols ]))


In [76]:
# y_bin as binary target (0 or 1) --> where ArrivalDelayGroups = 0 means less than 15min delay
df["BadFlight"] = ((df['ArrivalDelayGroups'] > 0) | (df['Cancelled'] > 0)).astype(int)

y_bin = df["BadFlight"]


In [22]:
# y_num as multi-class target (as classes)
df["ArrivalDelayGroups"]=df["ArrivalDelayGroups"].fillna("Cancelled")

buckets2 = {
    0:[-1.0, -2.0, 0],
    1: [1.0, 2.0],
    2: [3.0, 4.0, 5.0, 6.0, 7.0],
    3: [8.0, 9.0, 10.0, 11.0, 12.0, 'Cancelled']
}

def map_to_bucket(i):
    for bucket_name,bucket_values in buckets2.items():
        if i in bucket_values:
            return bucket_name


# Map original classes to new buckets using the function
df['ArrivalDelay_Groups_y_num'] = df['ArrivalDelayGroups'].apply(map_to_bucket)

y_num = df['ArrivalDelay_Groups_y_num']
# y_num.sample(20)


In [94]:
from sklearn.model_selection import train_test_split

# train-test split on y_bin
(X_train_bin, X_test_bin, y_train_bin, y_test_bin) = train_test_split(X_final, y_bin, test_size = .3)
print(X_train_bin.shape)
print(y_train_bin.shape)


(91268, 771)
(91268,)


In [25]:
from sklearn.model_selection import train_test_split

# train-test split on y_num
(X_train_num, X_test_num, y_train_num, y_test_num) = train_test_split(X_final, y_num, test_size = .3)
print(X_train_num.shape)
print(y_train_num.shape)


(91268, 775)
(91268,)


In [43]:
# Building a Regular Tree as Baseline
# Created Bagged Trees
# Ran a Random Forest with no Class Weighting (ran a feature importance plot as a QC tool)
# Random Forest with Bootstrat Class Weighting
# Ran a AdaBoost with and without the DEP_DELAY
# RAN Gradient Boosted Trees with and without the DEP_DELAY
# RAN XGBoost with and without the DEP_DELAY


# add recall etc measures
# take out zero data rows and validate/cross validate - data balancing (taking out the zeros) based on larger dataset
# cross validation look at sample, train with loop 20% removing columns where delay = 0 //


# Target Classification

In [78]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer, precision_score, recall_score, accuracy_score, f1_score
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix


### 1. DecisionTreeClassifier - binary

In [26]:

# Instantiate model
tree_clf = DecisionTreeClassifier()

# Hyperparameter Grid
grid_params = {'criterion': ['gini', 'entropy'],
               'max_depth': [9,10,11],
               'min_samples_split': [2,3,4],
               'min_samples_leaf': [7,8,9],
               'random_state': [42]
              }

# scorers = {
#   'precision_score': make_scorer(precision_score),
#   'recall_score': make_scorer(recall_score),
#   'accuracy_score': make_scorer(accuracy_score),
#   'f1_score': make_scorer(f1_score)
# }

# Instantiate Grid Search
search_tree = GridSearchCV(
    tree_clf,
    grid_params,
    scoring = 'accuracy',
    cv = 5,
    n_jobs=-1 # parallelize computation
)

# Fit data to Grid Search
search_tree.fit(X_train_bin, y_train_bin)
print(search_tree.best_estimator_)
print(search_tree.best_score_)
print(search_tree.best_params_)
print(search_tree.scorer_)


# tree_clf = DecisionTreeClassifier(max_depth=2, random_state=42, scoring='recall', cv = 5)
# tree_clf.fit(X_train_bin,y_train_bin)
# print(tree_clf.score(X_test_bin, y_test_bin))


KeyboardInterrupt: 

In [79]:
tree_clf = DecisionTreeClassifier(criterion='gini', max_depth=11, min_samples_leaf=9, min_samples_split=2, random_state=42,)
tree_clf.fit(X_train_bin, y_train_bin)
y_preds_bin = tree_clf.predict(X_test_bin)
print('accuracy: %.3f' % accuracy_score(y_preds_bin,y_test_bin))
print('f1_score: %.3f' % f1_score(y_test_bin, y_preds_bin, average='binary'))
print('recall: %.3f' % recall_score(y_test_bin, y_preds_bin,average='binary'))
print('precision: %.3f' % precision_score(y_test_bin, y_preds_bin,average='binary'))


print("Confusion Matrix: ", confusion_matrix(y_test_bin,y_preds_bin))


accuracy: 0.593
f1_score: 0.647
recall: 0.701
precision: 0.600
Confusion Matrix:  [[ 8613  9708]
 [ 6211 14583]]


In [80]:

tree_clf = DecisionTreeClassifier(criterion='gini', max_depth=11, min_samples_leaf=9, min_samples_split=2, random_state=42,)
tree_clf.fit(X_train_bin,y_train_bin)
cv_tree = cross_val_score(tree_clf, X_train_bin, y_train_bin, cv=5)
cv_tree.mean()


0.5894728508001833

### 1-b DecisionTreeClassifier - classes

In [98]:

# Instantiate model
tree_clf = DecisionTreeClassifier()

# Hyperparameter Grid
grid_params = {'criterion': ['gini', 'entropy'],
               'max_depth': [9,10,11],
               'min_samples_split': [2,3,4],
               'min_samples_leaf': [7,8,9],
               'random_state': [42]
              }

# scorers = {
#   'precision_score': make_scorer(precision_score),
#   'recall_score': make_scorer(recall_score),
#   'accuracy_score': make_scorer(accuracy_score),
#   'f1_score': make_scorer(f1_score)
# }

# Instantiate Grid Search
search_tree = GridSearchCV(
    tree_clf,
    grid_params,
    scoring = 'accuracy',
    cv = 5,
    n_jobs=-1 # parallelize computation
)

# Fit data to Grid Search
search_tree.fit(X_train_num, y_train_num)
print(search_tree.best_estimator_)
print(search_tree.best_score_)
print(search_tree.best_params_)
print(search_tree.scorer_)


DecisionTreeClassifier(criterion='entropy', max_depth=9, min_samples_leaf=9,
                       random_state=42)
0.7261006609049314
{'criterion': 'entropy', 'max_depth': 9, 'min_samples_leaf': 9, 'min_samples_split': 2, 'random_state': 42}
make_scorer(accuracy_score)


In [81]:
tree_clf = DecisionTreeClassifier(criterion='gini', max_depth=9, min_samples_leaf=9, min_samples_split=2, random_state=42,)
tree_clf.fit(X_train_num, y_train_num)
y_preds_num = tree_clf.predict(X_test_num)
print('accuracy: %.3f' % accuracy_score(y_preds_num,y_test_num))
print('f1_score: %.3f' % f1_score(y_test_num, y_preds_num, average='macro'))
print('recall: %.3f' % recall_score(y_test_num, y_preds_num,average='macro'))
print('precision: %.3f' % precision_score(y_test_num, y_preds_num,average='macro'))


print("Confusion Matrix: ", confusion_matrix(y_test_num,y_preds_num))


accuracy: 0.481
f1_score: 0.247
recall: 0.288
precision: 0.384
Confusion Matrix:  [[16877  1080    67   186]
 [ 8183  1615    81   166]
 [ 4720   916    92   114]
 [ 4152   572    54   240]]


In [82]:
tree_clf = DecisionTreeClassifier(criterion='gini', max_depth=11, min_samples_leaf=9, min_samples_split=2, random_state=42,)
tree_clf.fit(X_train_num,y_train_num)
cv_tree = cross_val_score(tree_clf, X_train_num, y_train_num, cv=5)
cv_tree.mean()


KeyboardInterrupt: 

### 2. RandomForestClassifier - binary

In [43]:


# Instantiate model
rf_clf = RandomForestClassifier()

# Hyperparameter Grid
grid_params = {'max_depth': [9,10,11],
               'random_state': [42]
              }

scorers = {
  'precision_score': make_scorer(precision_score),
  'recall_score': make_scorer(recall_score),
  'accuracy_score': make_scorer(accuracy_score),
  'f1_score': make_scorer(f1_score)
}

# Instantiate Grid Search
search_rf = GridSearchCV(
    rf_clf,
    grid_params,
    scoring = 'recall',
    cv = 5,
    n_jobs=-1 # parallelize computation
)

# Fit data to Grid Search
search_rf.fit(X_train_bin, y_train_bin)
print(search_rf.best_estimator_)
print(search_rf.best_score_)
print(search_rf.best_params_)
print(search_rf.scorer_)


RandomForestClassifier(max_depth=9, random_state=42)
0.7446517539400103
{'max_depth': 9, 'random_state': 42}
make_scorer(accuracy_score)


In [96]:
###########################################
###########################################
######## USE THIS MODEL FOR NOW ###########
###########################################
###########################################

rf_clf = RandomForestClassifier(max_depth=3, random_state=42)
rf_clf.fit(X_train_bin, y_train_bin)
y_preds_bin = rf_clf.predict(X_test_bin)
print('accuracy: %.3f' % accuracy_score(y_preds_bin,y_test_bin))
print('f1_score: %.3f' % f1_score(y_test_bin, y_preds_bin, average='binary'))
print('recall: %.3f' % recall_score(y_test_bin, y_preds_bin,average='binary'))
print('precision: %.3f' % precision_score(y_test_bin, y_preds_bin,average='binary'))


print("Confusion Matrix: ", confusion_matrix(y_test_bin,y_preds_bin))


accuracy: 0.535
f1_score: 0.693
recall: 0.989
precision: 0.533
Confusion Matrix:  [[  451 17953]
 [  224 20487]]


In [55]:
%cd ../flightdelay/pickle
%pwd


/home/maria/code/mariajoi/flightdelay/flightdelay/pickle


'/home/maria/code/mariajoi/flightdelay/flightdelay/pickle'

In [3]:
%cd ../pickle
# Export Pipeline as pickle file

from sklearn.pipeline import make_pipeline

# Add estimator
model = RandomForestClassifier(max_depth=5, random_state=42)

# Create and Fit Pipeline
model_pipeline = make_pipeline(preproc, model)
model_pipeline.fit(X_trans,y_bin)

with open("fitted_model_pipeline_test.pkl", "wb") as file:
    pickle.dump(model_pipeline, file)


/Users/ronjaboehmer/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-packages/IPython/core/magics/osm.py:393: UserWarning: using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})


[Errno 2] No such file or directory: '../pickle'
/Users/ronjaboehmer/code/mariajoi/flightdelay/notebooks


NameError: name 'RandomForestClassifier' is not defined

In [ ]:
with open("fitted_model_pipeline_test.pkl", "wb") as file:
    pickle.dump(model_pipeline, file)

In [2]:
model

NameError: name 'model' is not defined

In [34]:
rf_clf = RandomForestClassifier(max_depth=9, random_state=42)
rf_clf.fit(X_train_bin,y_train_bin)
cv_rf = cross_val_score(rf_clf, X_train_bin, y_train_bin, cv=5)
cv_rf.mean()


0.597011048300085

### 2-b RandomForestClassifier - classes

In [105]:


# Instantiate model
rf_clf = RandomForestClassifier()

# Hyperparameter Grid
grid_params = {'max_depth': [9,10,11],
               'random_state': [42]
              }

scorers = {
  'precision_score': make_scorer(precision_score),
  'recall_score': make_scorer(recall_score),
  'accuracy_score': make_scorer(accuracy_score),
  'f1_score': make_scorer(f1_score)
}

# Instantiate Grid Search
search_rf = GridSearchCV(
    rf_clf,
    grid_params,
    scoring = 'accuracy',
    cv = 5,
    n_jobs=-1 # parallelize computation
)

# Fit data to Grid Search
search_rf.fit(X_train_num, y_train_num)
print(search_rf.best_estimator_)
print(search_rf.best_score_)
print(search_rf.best_params_)
print(search_rf.scorer_)


RandomForestClassifier(max_depth=9, random_state=42)
0.741085409252669
{'max_depth': 9, 'random_state': 42}
make_scorer(accuracy_score)


In [35]:
rf_clf = RandomForestClassifier(max_depth=9, random_state=42)
rf_clf.fit(X_train_num, y_train_num)
y_preds_num = rf_clf.predict(X_test_num)
print('accuracy: %.3f' % accuracy_score(y_preds_num,y_test_num))
print('f1_score: %.3f' % f1_score(y_test_num, y_preds_num, average='macro'))
print('recall: %.3f' % recall_score(y_test_num, y_preds_num,average='macro'))
print('precision: %.3f' % precision_score(y_test_num, y_preds_num,average='macro'))


print("Confusion Matrix: ", confusion_matrix(y_test_num,y_preds_num))


accuracy: 0.466
f1_score: 0.159
recall: 0.250
precision: 0.116
Confusion Matrix:  [[18210     0     0     0]
 [10045     0     0     0]
 [ 5842     0     0     0]
 [ 5018     0     0     0]]


/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [36]:
rf_clf = RandomForestClassifier(max_depth=9, random_state=42)
rf_clf.fit(X_train_num,y_train_num)
cv_rf = cross_val_score(rf_clf, X_train_num, y_train_num, cv=5)
cv_rf.mean()


0.46629705882580685

### 3. GradientBoostingClassifier

In [61]:

# Instantiate model
gb_clf = GradientBoostingClassifier()

# Hyperparameter Grid
grid_params = {'max_depth': [1,5,10],
               'n_estimators': [100,150,200],
               'learning_rate': [0.001, 0.01, 0.1],
               'random_state': [42]
              }

scorers = {
  'precision_score': make_scorer(precision_score),
  'recall_score': make_scorer(recall_score),
  'accuracy_score': make_scorer(accuracy_score),
  'f1_score': make_scorer(f1_score)
}

# Instantiate Grid Search
search_gb = GridSearchCV(
    gb_clf,
    grid_params,
    scoring = 'accuracy',
    cv = 5,
    n_jobs=-1 # parallelize computation
)

# Fit data to Grid Search
search_gb.fit(X_train_bin, y_train_bin)
print(search_gb.best_estimator_)
print(search_gb.best_score_)
print(search_gb.best_params_)
print(search_gb.scorer_)


GradientBoostingClassifier(max_depth=1, random_state=42)
0.7475038129130656
{'learning_rate': 0.1, 'max_depth': 1, 'n_estimators': 100, 'random_state': 42}
make_scorer(accuracy_score)


In [37]:
gb_clf = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=1, random_state=42)
gb_clf.fit(X_train_bin, y_train_bin)
y_preds_bin = gb_clf.predict(X_test_bin)
print('accuracy: %.3f' % accuracy_score(y_preds_bin,y_test_bin))
print('f1_score: %.3f' % f1_score(y_test_bin, y_preds_bin, average='binary'))
print('recall: %.3f' % recall_score(y_test_bin, y_preds_bin,average='binary'))
print('precision: %.3f' % precision_score(y_test_bin, y_preds_bin,average='binary'))


print("Confusion Matrix: ", confusion_matrix(y_test_bin,y_preds_bin))


accuracy: 0.599
f1_score: 0.657
recall: 0.733
precision: 0.596
Confusion Matrix:  [[ 8366 10215]
 [ 5480 15054]]


In [38]:
gb_clf = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=1, random_state=42)
gb_clf.fit(X_train_bin,y_train_bin)
cv_gb = cross_val_score(gb_clf, X_train_bin, y_train_bin, cv=5)
cv_gb.mean()


0.5962769410109591

### 3-b GradientBoostClassifier

In [110]:

# Instantiate model
gb_clf = GradientBoostingClassifier()

# Hyperparameter Grid
grid_params = {'max_depth': [1,5,10],
               'n_estimators': [100,150,200],
               'learning_rate': [0.001, 0.01, 0.1],
               'random_state': [42]
              }

scorers = {
  'precision_score': make_scorer(precision_score),
  'recall_score': make_scorer(recall_score),
  'accuracy_score': make_scorer(accuracy_score),
  'f1_score': make_scorer(f1_score)
}

# Instantiate Grid Search
search_gb = GridSearchCV(
    gb_clf,
    grid_params,
    scoring = 'accuracy',
    cv = 5,
    n_jobs=-1 # parallelize computation
)

# Fit data to Grid Search
search_gb.fit(X_train_num, y_train_num)
print(search_gb.best_estimator_)
print(search_gb.best_score_)
print(search_gb.best_params_)
print(search_gb.scorer_)


GradientBoostingClassifier(learning_rate=0.001, max_depth=1, random_state=42)
0.741085409252669
{'learning_rate': 0.001, 'max_depth': 1, 'n_estimators': 100, 'random_state': 42}
make_scorer(accuracy_score)


In [39]:
gb_clf = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=1, random_state=42)
gb_clf.fit(X_train_num, y_train_num)
y_preds_num = gb_clf.predict(X_test_num)
print('accuracy: %.3f' % accuracy_score(y_preds_num,y_test_num))
print('f1_score: %.3f' % f1_score(y_test_num, y_preds_num, average='macro'))
print('recall: %.3f' % recall_score(y_test_num, y_preds_num,average='macro'))
print('precision: %.3f' % precision_score(y_test_num, y_preds_num,average='macro'))


print("Confusion Matrix: ", confusion_matrix(y_test_num,y_preds_num))


accuracy: 0.471
f1_score: 0.184
recall: 0.259
precision: 0.248
Confusion Matrix:  [[17877   332     0     1]
 [ 9489   554     1     1]
 [ 5480   358     0     4]
 [ 4772   245     0     1]]


In [40]:
gb_clf = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=1, random_state=42)
gb_clf.fit(X_train_num,y_train_num)
cv_gb = cross_val_score(gb_clf, X_train_num, y_train_num, cv=5)
cv_gb.mean()


KeyboardInterrupt: 

### 4. XGBoost Classifier

In [63]:


# Instantiate model
xgb_clf = XGBClassifier()

# Hyperparameter Grid
grid_params = {'max_depth': [1,5,10],
               'n_estimators': [50,100,150,200],
               'learning_rate': [0.001, 0.01, 0.1],
               'random_state': [42],
               'subsample': [0.999],
                'verbosity': [0]
              }

scorers = {
  'precision_score': make_scorer(precision_score),
  'recall_score': make_scorer(recall_score),
  'accuracy_score': make_scorer(accuracy_score),
  'f1_score': make_scorer(f1_score)
}

# Instantiate Grid Search
search_xgb = GridSearchCV(
    xgb_clf,
    grid_params,
    scoring = 'recall',
    cv = 5,
    n_jobs=-1 # parallelize computation
)

# Fit data to Grid Search
search_xgb.fit(X_train_bin, y_train_bin)
print(search_xgb.best_estimator_)
print(search_xgb.best_score_)
print(search_xgb.best_params_)
print(search_xgb.scorer_)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=10, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, random_state=42, ...)
0.19295774647887323
{'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 200, 'random_state': 42, 'subsample': 0.999, 'verbosity': 0}
make_scorer(recall_score, average=binary)


In [41]:

xgb_clf = XGBClassifier(n_estimators=200, learning_rate=0.1, max_depth=10, subsample= 0.999, random_state=42)
xgb_clf.fit(X_train_bin, y_train_bin)
y_preds_bin = xgb_clf.predict(X_test_bin)
print('accuracy: %.3f' % accuracy_score(y_preds_bin,y_test_bin))
print('f1_score: %.3f' % f1_score(y_test_bin, y_preds_bin, average='binary'))
print('recall: %.3f' % recall_score(y_test_bin, y_preds_bin,average='binary'))
print('precision: %.3f' % precision_score(y_test_bin, y_preds_bin,average='binary'))


print("Confusion Matrix: ", confusion_matrix(y_test_bin,y_preds_bin))


accuracy: 0.623
f1_score: 0.653
recall: 0.675
precision: 0.632
Confusion Matrix:  [[10514  8067]
 [ 6673 13861]]


In [42]:
xgb_clf = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=1, random_state=42)
xgb_clf.fit(X_train_bin,y_train_bin)
cv_xgb = cross_val_score(xgb_clf, X_train_bin, y_train_bin, cv=5)
cv_xgb.mean()


0.5963207664214388

### 4-b XGBoost Classifier 

In [ ]:
# Instantiate model
xgb_clf = XGBClassifier()

# Hyperparameter Grid
grid_params = {'max_depth': [1,5,10],
               'n_estimators': [50,100,150,200],
               'learning_rate': [0.001, 0.01, 0.1],
               'random_state': [42],
               'subsample': [0.999],
                'verbosity': [0]
              }

scorers = {
  'precision_score': make_scorer(precision_score),
  'recall_score': make_scorer(recall_score),
  'accuracy_score': make_scorer(accuracy_score),
  'f1_score': make_scorer(f1_score)
}

# Instantiate Grid Search
search_xgb = GridSearchCV(
    xgb_clf,
    grid_params,
    scoring = 'recall',
    cv = 5,
    n_jobs=-1 # parallelize computation
)

# Fit data to Grid Search
search_xgb.fit(X_train_num, y_train_num)
print(search_xgb.best_estimator_)
print(search_xgb.best_score_)
print(search_xgb.best_params_)
print(search_xgb.scorer_)


In [43]:

xgb_clf = XGBClassifier(n_estimators=200, learning_rate=0.1, max_depth=10, subsample= 0.999, random_state=42)
xgb_clf.fit(X_train_num, y_train_num)
y_preds_num = xgb_clf.predict(X_test_num)
print('accuracy: %.3f' % accuracy_score(y_preds_num,y_test_num))
print('f1_score: %.3f' % f1_score(y_test_num, y_preds_num, average='macro'))
print('recall: %.3f' % recall_score(y_test_num, y_preds_num,average='macro'))
print('precision: %.3f' % precision_score(y_test_num, y_preds_num,average='macro'))


print("Confusion Matrix: ", confusion_matrix(y_test_num,y_preds_num))


accuracy: 0.487
f1_score: 0.287
recall: 0.310
precision: 0.390
Confusion Matrix:  [[16121  1644   148   297]
 [ 7342  2267   201   235]
 [ 4150  1308   176   208]
 [ 3624   766   135   493]]


In [44]:
xgb_clf = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=1, random_state=42)
xgb_clf.fit(X_train_num,y_train_num)
cv_xgb = cross_val_score(xgb_clf, X_train_num, y_train_num, cv=5)
cv_xgb.mean()


0.46798440045645745

### 5. AdaBoostClassifier

In [69]:

# Instantiate model
ada_clf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier())


# Hyperparameter Grid
grid_params = {'base_estimator__max_depth':[i for i in range(2,11,2)],
              'base_estimator__min_samples_leaf':[5,10],
              'n_estimators':[10,50,100],
              'learning_rate':[0.01,0.1]
              }

scorers = {
  'precision_score': make_scorer(precision_score),
  'recall_score': make_scorer(recall_score),
  'accuracy_score': make_scorer(accuracy_score),
  'f1_score': make_scorer(f1_score)
}

# Instantiate Grid Search
search_ada = GridSearchCV(
    ada_clf,
    grid_params,
    scoring = 'f1',
    cv = 5,
    n_jobs=-1, # parallelize computation
    verbose = 0
)

# Fit data to Grid Search
search_ada.fit(X_train_bin, y_train_bin)
print(search_ada.best_estimator_)
print(search_ada.best_score_)
print(search_ada.best_params_)
print(search_ada.scorer_)


/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-pack

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=6,
                                                         min_samples_leaf=10),
                   learning_rate=0.1, n_estimators=100)
0.28562893332761546
{'base_estimator__max_depth': 6, 'base_estimator__min_samples_leaf': 10, 'learning_rate': 0.1, 'n_estimators': 100}
make_scorer(f1_score, average=binary)


In [45]:
ada_clf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=6, min_samples_leaf=10), learning_rate=0.1, random_state=42)
ada_clf.fit(X_train_bin, y_train_bin)
y_preds_bin = ada_clf.predict(X_test_bin)
print('accuracy: %.3f' % accuracy_score(y_preds_bin,y_test_bin))
print('f1_score: %.3f' % f1_score(y_test_bin, y_preds_bin, average='binary'))
print('recall: %.3f' % recall_score(y_test_bin, y_preds_bin,average='binary'))
print('precision: %.3f' % precision_score(y_test_bin, y_preds_bin,average='binary'))


print("Confusion Matrix: ", confusion_matrix(y_test_bin,y_preds_bin))


/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


accuracy: 0.618
f1_score: 0.656
recall: 0.695
precision: 0.622
Confusion Matrix:  [[ 9905  8676]
 [ 6273 14261]]


In [46]:
ada_clf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=6, min_samples_leaf=10), learning_rate=0.1, random_state=42)
ada_clf.fit(X_train_bin,y_train_bin)
cv_ada = cross_val_score(ada_clf, X_train_bin, y_train_bin, cv=5)
cv_ada.mean()


/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-packages/sklearn/ensemble/_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/home/maria/.pyenv/versions/3.10.6/envs/flightdelay/lib/python3.10/site-pack

KeyboardInterrupt: 

### 5-b AdaBoostClassifier - classes

In [ ]:
# Instantiate model
ada_clf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier())


# Hyperparameter Grid
grid_params = {'base_estimator__max_depth':[i for i in range(2,11,2)],
              'base_estimator__min_samples_leaf':[5,10],
              'n_estimators':[10,50,100],
              'learning_rate':[0.01,0.1]
              }

scorers = {
  'precision_score': make_scorer(precision_score),
  'recall_score': make_scorer(recall_score),
  'accuracy_score': make_scorer(accuracy_score),
  'f1_score': make_scorer(f1_score)
}

# Instantiate Grid Search
search_ada = GridSearchCV(
    ada_clf,
    grid_params,
    scoring = 'recall',
    cv = 5,
    n_jobs=-1, # parallelize computation
    verbose = 0
)

# Fit data to Grid Search
search_ada.fit(X_train_num, y_train_num)
print(search_ada.best_estimator_)
print(search_ada.best_score_)
print(search_ada.best_params_)
print(search_ada.scorer_)


In [ ]:
ada_clf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=6, min_samples_leaf=10), learning_rate=0.1, random_state=42)
ada_clf.fit(X_train_num, y_train_num)
y_preds_num = ada_clf.predict(X_test_num)
print('accuracy: %.3f' % accuracy_score(y_preds_num,y_test_num))
print('f1_score: %.3f' % f1_score(y_test_num, y_preds_num, average='macro'))
print('recall: %.3f' % recall_score(y_test_num, y_preds_num,average='macro'))
print('precision: %.3f' % precision_score(y_test_num, y_preds_num,average='macro'))


print("Confusion Matrix: ", confusion_matrix(y_test_num,y_preds_num))


In [ ]:
ada_clf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=6, min_samples_leaf=10), learning_rate=0.1, random_state=42)
ada_clf.fit(X_train_num,y_train_num)
cv_ada = cross_val_score(ada_clf, X_train_num, y_train_num, cv=5)
cv_ada.mean()


In [87]:
scorer = make_scorer(accuracy_score)
scores = cross_val_score(
    estimator=xgb_clf,
    X=X_train_bin,
    y=y_train_bin,
    scoring=scorer,
    cv=5
)
print('CV  scores:',  scores)
print('CV accuracy:', (np.mean(scores), np.std(scores)))


CV  scores: [0.75088968 0.74377224 0.75357143 0.74285714 0.74642857]
CV accuracy: (0.7475038129130656, 0.004121950076627391)


In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier

# Instantiate model
weak_learner = KNeighborsClassifier(n_neighbors=3)
bagged_clf = BaggingClassifier(weak_learner, n_estimators=40)


ada_clf = AdaBoostClassifier(base_estimator=DecisionTreeClassifier())


# Hyperparameter Grid
grid_params = {'base_estimator__max_depth':[i for i in range(2,11,2)],
              'base_estimator__min_samples_leaf':[5,10],
              'n_estimators':[10,50,100],
              'learning_rate':[0.01,0.1]
              }

scorers = {
  'precision_score': make_scorer(precision_score),
  'recall_score': make_scorer(recall_score),
  'accuracy_score': make_scorer(accuracy_score),
  'f1_score': make_scorer(f1_score)
}

# Instantiate Grid Search
search_bag = GridSearchCV(
    bagged_clf,
    grid_params,
    scoring = 'f1',
    cv = 5,
    n_jobs=-1, # parallelize computation
    verbose = 0
)

# Fit data to Grid Search
search_ada.fit(X_train_bin, y_train_bin)
print(search_ada.best_estimator_)
print(search_ada.best_score_)
print(search_ada.best_params_)
print(search_ada.scorer_)


In [ ]:

# y_pred = rf.predict(X_test)
# print('recall: ', recall_score(y_test, y_pred, average='macro'))
# print('precision: ', precision_score(y_test, y_pred,  average='macro'))
# print('f1_score: ', f1_score(y_test, y_pred, average='macro'))
# idx = np.random.choice(np.arange(len(X_train)), 2000, replace=False)
# x_sample = X_train[idx]
# y_sample = y_train[idx]
# sfs = SequentialFeatureSelector(
#         estimator=xgb,
#         n_features_to_select=20,
#         direction='forward'
#     )

# sfs.fit(x_sample, y_sample)
# sfs.get_support()
# df.columns
# x_tr=sfs.transform(X_train)
# x_tes=sfs.transform(X_test)


## 2. Regressors for delay prediction in minutes

### Decision Tree Regressor

In [48]:
# from sklearn.tree import DecisionTreeRegressor
# from sklearn.model_selection import cross_validate

# tree = DecisionTreeRegressor(min_samples_split=9, max_depth=5, min_samples_leaf=5)

# cv_results = cross_validate(tree, X, y, scoring = "r2", cv=5)


# def plot_histogram_cv_results(cv_results):
#     # Calculating the std and the mean
#     std = cv_results['test_score'].std()
#     mean = cv_results['test_score'].mean()

#     # Getting the number of folds
#     n_cv = len(cv_results['test_score'])

#     # Building plot
#     plt.hist(cv_results['test_score'], bins=n_cv)

#     # Creating red lines
#     plt.vlines(mean, 0, 3, color='red', label=f'mean = {mean:.2f}')
#     plt.hlines(
#         3, mean - 1/2 * std, mean + 1/2 * std,
#         color='red', label=f'std = {std:.2f}', ls='dotted'
#     )

#     # Setting the title
#     plt.title('Histogram of R2 Scores During Cross-Validation')

#     # Setting the labels and xlim
#     plt.xlim((-1, 1))

#     plt.xlabel('r2')
#     plt.ylabel('number of folds')

#     # Showing the legend
#     plt.legend(loc='upper left')

#     plt.show()



# # Custom method
# plot_histogram_cv_results(cv_results)


In [49]:
# from sklearn.tree import DecisionTreeRegressor
# from sklearn.model_selection import cross_validate

# tree = DecisionTreeRegressor(min_samples_split=9, max_depth=5, min_samples_leaf=5)

# cv_results = cross_validate(tree, X, y, scoring = "r2", cv=5)

# # Custom method
# plot_histogram_cv_results(cv_results)


In [52]:
# cv_results['test_score'].mean()


### RandomForestRegressor

In [ ]:
from sklearn.ensemble import RandomForestRegressor

forest = RandomForestRegressor(n_estimators=500)

cv_results = cross_validate(forest, X, y, scoring = "r2", cv=5)

plot_histogram_cv_results(cv_results)


### GradientBoostingRegressor

In [91]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3
)


### XGB Regressor

In [51]:
# from xgboost import XGBRegressor

# xgb_reg = XGBRegressor(max_depth=10, n_estimators=50, learning_rate=0.1)

# xgb_reg.fit(X_train, y_train,
#     # stop iterating when eval loss increases 5 times in a row
#     early_stopping_rounds=5
# )

# y_pred = xgb_reg.predict(X_test)

#     # evaluate loss at each iteration
#     # eval_set=[(X_train, y_train), (X_val, y_val)]


### ADABoostRegressor

In [50]:
# from sklearn.ensemble import AdaBoostRegressor

# adaboost = AdaBoostRegressor(
#     DecisionTreeRegressor(max_depth=3),
#     n_estimators=50)

# cv_results = cross_validate(adaboost, X, y, scoring = "r2", cv=5)

# plot_histogram_cv_results(cv_results)
